-- 01_rfm_features.sql
-- Validates the synthetic rfm_scores table generated by generate_synthetic_data.py
-- Source: customer-churn-492703.customer_intelligence.rfm_scores (200,000 rows)

SELECT
  segment,
  COUNT(*)                      AS customers,
  ROUND(AVG(churned), 3)        AS churn_rate,
  ROUND(AVG(recency_days), 1)   AS avg_recency,
  ROUND(AVG(frequency), 1)      AS avg_frequency,
  ROUND(AVG(monetary), 2)       AS avg_monetary
FROM `customer-churn-492703.customer_intelligence.rfm_scores`
GROUP BY segment
ORDER BY segment